### ISSUE TITLE
可以规范一下第三方jar的版本

### ISSUE THREAD

**Issue by slieer** [houbb/pinyin#10]
版本问题：
![image](https://user-images.githubusercontent.com/1211813/108493827-c6982580-72e1-11eb-9b01-f3b6e0ee74cf.png)

是不是修改一下这里？
![image](https://user-images.githubusercontent.com/1211813/108494144-28f12600-72e2-11eb-992d-08ac5c045430.png)

**Comment by houbb** [comment]
v0.1.5 已优化，忘记关闭了。

感谢提醒：）
