### ISSUE TITLE
我试了好多次，结果pinyin4j速度更快啊

### ISSUE THREAD

**Issue by feier0908** [houbb/pinyin#11]
![image](https://user-images.githubusercontent.com/31612688/112310882-076bcb80-8ce0-11eb-805f-4e8e4bb5a114.png)
有截图为证

**Comment by houbb** [comment]
如果单条的话，可能是的。

实际使用，pinyin 可以首先执行一次预热。

下面是比较 1000000 次的例子，可以自己测试下。

可以看这个 [BenchmarkTest.java](https://github.com/houbb/pinyin/blob/master/src/test/java/com/github/houbb/pinyin/test/benchmark/BenchmarkTest.java)

**Comment by feier0908** [comment]
看了你的测试demo了，你里面用的pinyin4j是2.5.0，而2.5.1效果好很多，毕竟2.5.0是2013年的版本，也是pinyin4j的第一版，效果确实一般，2.5.1在词组上和咱们的不差上下，确实稍慢了一点！如果挂载外部字典，速度也很不错！单字识别方面远远超过咱们！我觉得主要问题是字典格式问题，要是能优化字典加载或许性能

**Comment by feier0908** [comment]
java既然是用的Unicode编码，建议那些基本单字字典用Unicode汉字对照拼音，音标用数字表示，这样内存寻址就快很多！咱们这个工具确实比pinyin4j用着方便，调用是更简洁了！加油！自定义字典方便!希望能真正的早日超过他！另外，考虑到手机安卓开发人员也会用到，体积是还要考虑优化，或者可以专门出个精简的版本，体积小些！

**Comment by feier0908** [comment]
至于我的那个截图，其实是翻译了将近一万字的文章，如果翻译文章2.5.1版本的pinyin4j略快于咱们

**Comment by houbb** [comment]
感谢建议，我后面会尝试验证优化下。我当时测试的时候使用的 v2.5.0，没注意小版本的性能差异。

性能略快，应该是 pinyin4j 默认不支持分词导致的，这样准确性差些。还要再接再厉！

**Comment by houbb** [comment]
v0.2.0 做了一点小的优化，和 v2.5.1 进行对比，如果提前预热（生产也建议这样使用），性能是远优于  pinyin4j 的。

[benchmark](https://github.com/houbb/pinyin#benchmark)

如果不进行预热，性能应该会差，是以后优化的重点。
