### ISSUE TITLE
有些汉字无法转换

### ISSUE THREAD

**Issue by cugljd** [houbb/pinyin#16]
如：凤头䴙䴘等。

PinyinHelper.toPinyin("凤头䴙䴘") -> fèng tóu 䴙 䴘
PinyinHelper.toPinyin("黑喉石䳭") -> hēi hóu shí 䳭

**Comment by houbb** [comment]
嗯，这个支持用户自定义：[自定义](https://github.com/houbb/pinyin#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%8B%BC%E9%9F%B3%E8%AF%8D%E5%BA%93)

或者等我做一下升级，好了这里回复你。

**Comment by cugljd** [comment]
这些汉字我看到在 [pinyin_dict_char.txt](https://github.com/houbb/pinyin/blob/master/src/main/resources/pinyin_dict_char.txt) 里面是有的。

**Comment by houbb** [comment]
V0.3.1 已修正这个问题，原来对于汉字的限定过于严格，导致生僻词无法转换。

```java
Assert.assertEquals("fèng tóu pì tī", PinyinHelper.toPinyin("凤头䴙䴘"));
Assert.assertEquals("hēi hóu shí jí", PinyinHelper.toPinyin("黑喉石䳭"));
```
