### ISSUE TITLE
pinyin_dict_char_define.txt的路径如何自定义呢？

### ISSUE THREAD

**Issue by wuzhike666** [houbb/pinyin#23]
pinyin_dict_char_define.txt的路径如何自定义呢？

**Comment by houbb** [comment]
放在 resource 根目录即可，可以自测一下。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: wuzhike666 ***@***.***&gt;
发送时间: 2023年4月21日 16:07
收件人: houbb/pinyin ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [houbb/pinyin] pinyin_dict_char_define.txt的路径如何自定义呢？ (Issue #23)





 
pinyin_dict_char_define.txt的路径如何自定义呢？
