### ISSUE TITLE
关于首拼模式，自定义是否带空格。

### ISSUE THREAD

**Issue by TxcA** [houbb/pinyin#3]
你好，感谢封装，用过几个拼音库，都在不断的学习和尝试换更新的库。
这里提个使用中遇到的问题，FIRST_LETTER首拼模式下，是否可以多传个参数，不自动加空格（或者多一个没空格的枚举）。
这边用来取中文后做模糊匹配，目前调用完toPinYin后，还得replaceAll(" ", "")一次。
感谢

**Comment by houbb** [comment]
好的，本周内有时间加一个这个特性。

**Comment by houbb** [comment]
[v0.1.2 已支持自定义连接符号。](https://github.com/houbb/pinyin#%E6%8C%87%E5%AE%9A%E8%BF%9E%E6%8E%A5%E7%AC%A6%E5%8F%B7)

```java
final String text = "我爱中文";
Assert.assertEquals("wazw", PinyinHelper.toPinyin(text, PinyinStyleEnum.FIRST_LETTER, StringUtil.EMPTY));
```
