### ISSUE TITLE
能否给分词加个开关？

### ISSUE THREAD

**Issue by zhfish** [houbb/pinyin#5]
现在我是在转拼音之后，手动trim掉空格
但是有些情况，中英文混合，英文单词中间的空格被误trim了
希望可以关掉分词

很好用，效率不错

**Comment by houbb** [comment]
空格的拼接方式可以指定 [拼音拼接指定连接方式](https://github.com/houbb/pinyin#%E6%8C%87%E5%AE%9A%E8%BF%9E%E6%8E%A5%E7%AC%A6%E5%8F%B7)，所以不需要手动 trim。你可以尝试下能否解决问题。

分词是为了多音字的准确性，实现是可以根据自己的需求指定的。

**Comment by zhfish** [comment]
我指的并不是连接符，那看来不是分词问题
我找一下测试案例，我记得当时是4个字， 然后输出了 `a bcd`这样的格式
