### ISSUE TITLE
重复引入依赖错误

### ISSUE THREAD

**Issue by RevisitMoon** [houbb/pinyin#8]
主程序里引入了
<heaven.version>0.1.113</heaven.version>

在nlp-common
再次引入了
<heaven.version>0.1.76</heaven.version>

**Comment by houbb** [comment]
这个是不影响使用的，根据 maven 依赖优先级，会使用 0.1.113 版本。

v0.1.5 版本已经排除了重复依赖，感谢提醒。

**Comment by RevisitMoon** [comment]
好的.某些程序员强迫症.哈哈哈
